### ISSUE TITLE
Inconsistent creation of output on Windows

### ISSUE THREAD

**Issue by Chaoste** [danijar/handout#1]
Hi Dani!

1st issue!😄 

Just tried your example and made it run by executing from the terminal. But I already struggled with setting up my Atom IDE so I can execute it from there. I used "atom-run-python" and "atom-python-virtualenv" so I can execute my script on the go in the related virtualenv. Executing it with this setting leads to some kind of bug. The plots are located in the same directory as "example.py" ("example.py-L48-0.png", etc.) while HTML, js, css are placed in the output directory.

Since it might be related to the executing directory I tried to execute "python example.py" in the terminal but in its parent directory (`python repo/example.py`). This even leads to an execution error:
```
(venv) C:\Users\Thomas\HPI> python .\MA\example.py
Traceback (most recent call last):
  File ".\MA\example.py", line 48, in <module>
    doc.display(fig)  # Display the figure below this line.
  File "C:\Users\Thomas\HPI\MA\venv\lib\site-packages\handout\handout.py", line 26, in display
    figure.savefig(filename)
  File "C:\Users\Thomas\HPI\MA\venv\lib\site-packages\matplotlib\figure.py", line 1834, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\Thomas\HPI\MA\venv\lib\site-packages\matplotlib\backend_bases.py", line 2267, in print_figure
    **kwargs)
  File "C:\Users\Thomas\HPI\MA\venv\lib\site-packages\matplotlib\backends\backend_agg.py", line 512, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'output\\.\\MA\\example.py-L48-0.png'
```
An empty output directory is created next to my repository.

### Environment
- Windows 8
- Python 3.6.0
- handout==0.2.2

Hope this helps you tracking down this bug,
Thomas

**Comment by danijar** [comment]
Thanks for testing, Thomas! I'm looking into this. The handout is supposed to be stored in the directory that is passed to `handout.Handout(directory)`. Would you mind trying to pass an absolute path there? If this doesn't help, could you try `python example.py` instead of calling Python from the outside directory?

**Comment by danijar** [comment]
I think this is fixed now. Could you verify, please?

**Comment by Chaoste** [comment]
Hey Danijar,

I tested from a parent and a sub directory. It works like a charm ;) Might be worthful to mentioned in the docs that the output directory is created in the working directory and not next to the executed python script.

Greetings,
Thomas

**Comment by danijar** [comment]
Great to hear! Thanks for testing and feedback.
