### ISSUE TITLE
Custom html document title

### ISSUE THREAD

**Issue by epogrebnyak** [danijar/handout#13]
Html file title is currently is hardcoded Handout. A user might want to override it with custom title, something like `"Jane's awesome notebook"`

https://github.com/danijar/handout/blob/00d9c58fc512f30feb8df83808e21adb62673abb/handout/handout.py#L111-L116

Implemetation would require small change in constructor as below:

```
class Handout(object):

  def __init__(self, directory, title="Handout"):
```

**Comment by danijar** [comment]
Thanks for the feature request, that seems very doable.

**Comment by epogrebnyak** [comment]
I can do a PR for this feature, it looks rather straight-forward. 

Is there a unit testing strategy that you have in mind - maybe, pytest? Can move testing discussion to a separate issue if you want.

**Comment by epogrebnyak** [comment]
Closed with https://github.com/danijar/handout/pull/14
