### ISSUE TITLE
Name of an output html file can be {__file__}.html

### ISSUE THREAD

**Issue by epogrebnyak** [danijar/handout#16]
Similar to #13 the name of an output html file can be `{__file__}.html`, instead of hardcoded `index.html` (if it is possible to track and pass source file name, but seems realistic).

This way `model.py` will have an output `model.html`. This feature should open the way to ensembles/collections of handouts. 

https://github.com/danijar/handout/blob/f89ec584d4e0e96a5293cc9c1fff69cd1e3e6bdf/handout/handout.py#L98

**Comment by danijar** [comment]
If people want to build websites with Python Handout, I think more than just the name of the HTML file needs to be addressed. For example, writing multiple handouts to the same output directory would lead to filename collisions for images, etc. Let's track the idea in #17. I'm closing this for now, but let me know if I missed a point about the idea.

**Comment by epogrebnyak** [comment]
Maybe for the documentation - different handounts should have different directories, and the responsibility is on the caller side to provide a corresponding directory.
