### ISSUE TITLE
PyPi package needs a description

### ISSUE THREAD

**Issue by tdunning** [danijar/handout#19]
Hard to understand the package without it. Finding one's way back to github is probably beyond many.

**Comment by danijar** [comment]
Yes, we just need to add the readme to the release packages. Thanks for suggesting.

**Comment by danijar** [comment]
This is how to do it: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/

**Comment by epogrebnyak** [comment]
Should we just add this?

```python

from pathlib import Path

setup(
      # ...
      long_description = Path('README.md').read_text(),
      long_description_content_type="text/markdown",
)

**Comment by danijar** [comment]
Yes, that would be great!
