### ISSUE TITLE
Pandas Dataframe Display Support

### ISSUE THREAD

**Issue by Phutoast** [danijar/handout#30]
Hi, it would be great to have a handout that could generate/display a Dataframe table. Might be something like `doc.add_dataframe(df)`

**Comment by epogrebnyak** [comment]
I thought of tables too - might be a good feature!

Would `doc.add_dataframe(df)` need to  do anything beyond `doc.add_html(df.to_html())`?

**Comment by Phutoast** [comment]
Maybe when the table is very big, we might only show some parts of the start of the table and some parts at the end of the table (similar to jupyer notebook, when showing a big dataframe). 

This might be somewhat achieved using `max_rows` or `max_cols`.  More of like how we display the table itself. 

But generally, `doc.add_html(df.to_html())` is a good idea for a small table

**Comment by epogrebnyak** [comment]
Right! Jupyter also has scroll bars for the table and line shading, as more
advanced features, just to consider.

Maybe start with `doc.add_html(df.to_html())` as a placeholder and develop
on it later.

пн, 12 авг. 2019 г. в 17:45, Phu Sakulwongtana <notifications@github.com>:

**Comment by danijar** [comment]
Sounds good, I'll close this for now and add the documentation tag. We should include your one-liner in the user guide. If anybody has an actual need for more interactivity, feel free to open a new issue and we can discuss.
