### ISSUE TITLE
Making handout work with Jupyter

### ISSUE THREAD

**Issue by lucacerone** [danijar/handout#32]
First of all, thanks for creating handout!

Is there any plan to integrate Jupyter and Handout files in the future?
I think the combination of both would help solve lots of issues current notebooks have, while keeping the practical approach jupyter notebooks have!

I think if we could have in Python something similar to how Rstudio implemented notebooks (where you can easily commit text files) while keeping the flexibility of working interactively it would be a game changer!

Thanks again for your work!

**Comment by danijar** [comment]
Hi! Please see #25 and #33 and let me know if there are any function functionalities that you think would be useful in this regard. However, be aware that the premise of Python Handout is to write your code from a Python script rather than an interactive web interface.

**Comment by lucacerone** [comment]
Hi danijar thanks! I think the issues you linked cover different needs. For me the most useful way it would be to work as if I were using a Jupyter notebook, but having the advantages Handout offers (i.e. having the "notebook" code separated by the data and the artifacts needed to generate the output).

In this regard I think that Rmarkdown notebooks, as implemented by Rstudio, are the best compromise between the flexibility of interactive development and keeping the code under version control).

Thanks a lot again for your great work on Handout

**Comment by danijar** [comment]
Converting to and from Jupyter notebooks as discussed in #33 might help you. This way, you could work in Jupyter notebooks but commit Handout Python scripts in version control. It means you could also easily re-run a script without having to start Jupyter.
