### ISSUE TITLE
Use AST module to parse script rather than processing text line by line

### ISSUE THREAD

**Issue by danijar** [danijar/handout#34]
Branched from https://github.com/danijar/handout/issues/10#issuecomment-520612161:

> @danijar would you be open to a PR that uses the Python AST. Looking at this request and others, it might be worth to consider making the change to AST parsing, sooner rather then later. For instance one advantage could be, is that you choose to hide the doc.* code.

Hi @eiso, yes I think switching to AST could be good. I'd definitely look forward to a PR, although it'll likely take some back and forth until we converge on a design that works well for the library.

**Comment by epogrebnyak** [comment]
I think it is a good idea to branch a AST to a new issue. Probably a good step ahead is discussing how how we use source parsing in Handout class and how we can wrap a line-by-line  and AST parser under similar interface that Handout class would use.

Conceptually, from the source and from the add_*() functions we are getting dictionaries that relate a line to a list of blocks, usually of one block in list per line. Upon merging the source file blocks and user defined blocks we get a list of blocks that constitutes the handout content. The exporter will use a list of blocks to produce html or latex. 

Important to note we are getting the line numbers for user blocks at runtime through a clever inspect lookup @danjar made.

I see current sequence of events as follows: 

1. source code lines seen as list or dict of strings. 
2. lines are identified as code or text, converted to blocks
3. add_* functions create list of user blocks, registered by line number where add is called
4. user blocks injected after code lines upon merging of source code blocks and user blocks
5. blocks flattened to one list,
6. block list processed by html or latex exporter

Cleaning of empty lines and #handout pragma processing to be added to the above.

In AST representation source file will be represented as tree of statements. The add_х(). function will insert an extra statement in the source  file AST by line number, obtained at runtime? Or should we work by some other identifier in AST, different than line number, @eiso?

**Comment by danijar** [comment]
Note that the blocks change while the code is running, because we don't know what media future code will add before the interpreter gets to that line. AST won't help us here since Python is a dynamic language. This is why I think the existing way blocks are created is good. With this in mind, I'm actually quite skeptical about whether looking at the AST helps us at all, but I'm happy to discuss what the benefits would be either way.

**Comment by epogrebnyak** [comment]
@danjar, thanks for pointing out - is it true to say that user blocks are changing at runtime when add_x() functions are called, but not the source code blocks? I think the source code blocks are quite stable as they are determined to script text. Dealing with AST imo allows us to make smarter choices on how to convert text of script into script representing blocks, that is it. To me this functionality seems quite isolated from adding user blocks with add-text and similar functions. 

The only problem I see is that source blocks will be organized by statement in AST and injection of user blocks is done by line number, but this can be handled I think.

**Comment by danijar** [comment]
> Dealing with AST imo allows us to make smarter choices on how to convert text of script into script representing blocks, that is it.

Could you elaborate a bit on what exactly we might want to use this for?

**Comment by epogrebnyak** [comment]
Well, it's been in the comments in issues before:

- statement-level pragmas ([my example with coverage.py](https://github.com/danijar/handout/issues/10#issuecomment-519877996)) 
- [end of docstring exclude comment](https://github.com/danijar/handout/issues/10#issuecomment-518457662)
- option to exclude of all handout-related code as [@eiso suggested](https://github.com/danijar/handout/issues/10#issuecomment-520612161)

**Comment by danijar** [comment]
Okay I see. As mentioned, I don't see a benefit of statement-level excludes compared to a range exclude.

Hiding handout-related code is an interesting idea. I don't think it's worth the added complexity at this point though, and can't be fully solved with AST parsing anyway because Python is a very flexible language and things can change at run time.

I'm closing this for now, but we might want to reconsider at some point in the future when there are more reasons for using the AST.

**Comment by alexmojaki** [comment]
> I don't think it's worth the added complexity at this point though, and can't be fully solved with AST parsing anyway because Python is a very flexible language and things can change at run time.

What you can do is from within `doc.add_*` look up the stack until you find the frame with the code that's inserted into the document, then pass that to `[executing](https://github.com/alexmojaki/executing)` to find the AST node corresponding to the call. That would work regardless of whatever the user did at runtime. But it would raise some questions about the API. For example, if the user defined a function that does several things in addition to calling `doc.add_text()`, they probably don't want to hide that function, so maybe we could allow writing `doc.add_text(text, hide=False)`.
