### ISSUE TITLE
Generate handout every time the Python script is saved 

### ISSUE THREAD

**Issue by nicksspirit** [danijar/handout#36]
I am just discovering this package but I wonder the feasibility of __handout__ to support real time editing. 

I was envisioning having integrations with editors such as Visual Studio Code, Sublime Text or Atom  that would allow real time editing.

Your thoughts on this is much appreciated.

**Comment by danijar** [comment]
What do you mean by real time editing?

**Comment by nicksspirit** [comment]
So like i am wondering if handout can be used in a situation where by I can be editing a python file and then have some daemon or something run handout with every change in the source file and handout would be able to produce the output html.

I am curious to know if handout can function reliably in such a scenario.

**Comment by danijar** [comment]
Yes, just run the file on save. For example, on Linux you can install `inotify-tools` and run this in a terminal (see this [SuperUser question](https://superuser.com/q/181517/184125)):

```sh
while inotifywait -e close_write script.py; do python3 script.py; done
```

Is this what you're looking for?

**Comment by nicksspirit** [comment]
Yeah that sounds like what i am looking for. Are you aware of any tools similar to `inotify-tools` for windows??

**Comment by danijar** [comment]
I don't use Windows but according to this [StackOverflow question](https://stackoverflow.com/q/36951081/1079110) this batch script might work:

```
@echo off
:loop  
timeout -t 1 >nul  
for %%i in (script.py) do echo %%~ai|find "a">nul || goto :loop
python script.py
rem do workload
attrib -a script.py
goto :loop
```

Many text editors also allow to specify a command to run every time a file is saved. Please also look a bit into this by yourself if the script above doesn't work immediately. Closing this now.
