### ISSUE TITLE
Pathlib error when running setup.py on Linux

### ISSUE THREAD

**Issue by Uiuran** [danijar/handout#37]
Hi, is pathlib really a necessary dependency ? since: after install it gives:
~~~bash
    AttributeError: 'PosixPath' object has no attribute 'read_text'
~~~ 
can it be builted withou longdescription or with another text parser 
? (it seems that pathlib has to do with windows and .Net)

**Comment by danijar** [comment]
How are you installing Handout?

**Comment by epogrebnyak** [comment]
What system are you on? `pathlib` is a Python 3 library

**Comment by danijar** [comment]
If they have the `PosixPath` object I assume they're using Python 3. Maybe the standard library has a bug on Windows but either way, `read_text()` is only using in `setup.py` which you don't need to execute to just use the package.

**Comment by Uiuran** [comment]
i dont use windows, thats the point. but there may be some similar parser
to linux

**Comment by danijar** [comment]
How are you installing and running handout?

**Comment by epogrebnyak** [comment]
We can omit pathlib from setup.py, just to make things easier, less confusion in cases like this one.

**Comment by Uiuran** [comment]
DId i put on Windows ? sorry guys, maybe i was drunk. I simple dont know how it works in Windows.

**Comment by danijar** [comment]
No problem. The *Getting started* instructions in the README file are also valid for Windows.
