### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by kirk86** [danijar/handout#39]
Hi would it be too much trouble to ask for a conda package?

**Comment by danijar** [comment]
Like this? https://anaconda.org/conda-forge/handout

**Comment by kirk86** [comment]
Thanks that's great, sorry to bother I wasn't aware of it. Usually I don't use conda-forge because if you install even a single package from it next time you'll do `conda update --all` it will overwrite existing packages in your environment with equivalent ones from conda-forge and that behaviour might not be desirable.

**Comment by danijar** [comment]
No problem at all. I see that that's not always the ideal behavior. I'm not familiar with conda but please feel free to create a main conda package if you know how to do it.
