### ISSUE TITLE
Possible to hide some code?

### ISSUE THREAD

**Issue by henrikmarklund** [danijar/handout#40]
**Use case:** 
I'm using Handout as an alternative to ShareLatex/Notebook for my homework reports. The reports consists many plots and a few comments. 

**What I want to be able to do**
I want to hide some parts of my code that are not relevant to the reader of the report, but necessary to create my plots. For instance, I usually have several lines specifying formatting of my pyplots.

Thanks

**Comment by danijar** [comment]
```python
# handout: begin-exclude
fig, ax = plt.subplots()
ax.plot(np.sin(np.linspace(0, 20, 100)))
doc.add_figure(fig)
doc.show()
# handout: end-exclude
