### ISSUE TITLE
doc.show() will execute _generate method and rewrites index.html?

### ISSUE THREAD

**Issue by syahrulhamdani** [danijar/handout#41]
Hi, all. 
I want to make sure how `handout` renders the scripts. It looks like `doc.show()` will execute `_generate` method, append all the blocks, then render all of them, right? And then when `doc.show()` gets called again, it will re-render the whole blocks except with more `lineno`?

With this behavior, if someone writes more lines of script, maybe with more figures or videos, does it affect the time we need to run the script?

**Comment by danijar** [comment]
Yes, the doc gets updated on every `doc.show()`. This lets you see the progress of a long running script. It doesn't take a lot of time to render the HTML since the media elements are only written to disk once.
