### ISSUE TITLE
image misplaced to end of file

### ISSUE THREAD

**Issue by epogrebnyak** [danijar/handout#46]
I got to use handout for a simple jupyter-like visualisation and was adding an image in the middle of the file.

The image does show up, but at the end of file. This is not an intended behaviour, right? 

What can be causing it? I initially thought Spyder/ipython session could be the problem, 
but a standalone intepreter run does the same. 

Here is my output:
<https://epogrebnyak.github.io/sna-ru/handout/index.html>

Here is the code:
<https://github.com/epogrebnyak/sna-ru/issues/1>

**Comment by danijar** [comment]
Are you calling doc.show() after adding the image?

**Comment by epogrebnyak** [comment]
Indeed! Now I rememeber doc.show() pushes a queue of object sto html. 

Maybe add a docstring to https://github.com/danijar/handout/blob/b4d9ee5f31a68153cc35182d1c2f3fc9b04940dc/handout/handout.py#L97

For example:

```python 
"""Insert added items at this point in script and save to <outdir>/index.html"""
```
