### ISSUE TITLE
Need to install dependencies separately

### ISSUE THREAD

**Issue by thakreyn** [danijar/handout#49]
While installing the package by pip, it does not install dependencies like 'matplotlib', 'imageio' etc. These have to be installed separately. We can make some changes to the 'setup.py' to include all dependencies so that it becomes very convenient to install the entire thing with just one command.

**Comment by danijar** [comment]
Thanks for bringing this up! See https://github.com/danijar/handout/pull/50 for an explanation. Happy to continue discussing this if you feel strongly about it. You can also just install all the things with a single command via:

```
pip install handout matplotlib imageio imageio-ffmpeg
```
