### ISSUE TITLE
Support adding animations and videos

### ISSUE THREAD

**Issue by danijar** [danijar/handout#5]
`doc.add_video(tensor_or_filename)` to create GIFs or display anything the browser can display (e.g. MP4).

**Comment by danijar** [comment]
Done

**Comment by RoyiAvital** [comment]
Any chance for APNG (Animated PNG)?

**Comment by danijar** [comment]
We are using the imageio module, which [supports these file formats](https://imageio.readthedocs.io/en/stable/formats.html). There might be a way to extend imageio in case you want to go that route.
